name: Build Beta

on:
  push:
    branches:
      - beta

jobs:
  Android:
    name: Android
    runs-on: ubuntu-latest
    steps:
      - name: Check out git repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Cache Gradle Wrapper
        uses: actions/cache@v3
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}

      - name: Cache Gradle Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-caches-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-caches-

      - name: Cache Node Dependencies
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-caches-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-caches-

      - name: Install dependencies
        run: npm ci

      - name: Build Packages
        run: |
          cd android
          ./gradlew assembleDebug

      # Push tag to GitHub if package.json version's tag is not tagged
      - name: Get package version
        run: node -p -e '`PACKAGE_VERSION=${require("./package.json").version}`' >> $GITHUB_ENV

      - name: Generate file MD5
        run: |
          cd android/app/build/outputs/apk/release
          md5sum *.apk

      - name: Upload Artifact arm64-v8a
        uses: actions/upload-artifact@v3
        with:
          name: app-v${{ env.PACKAGE_VERSION }}-arm64-v8a-release
          path: android/app/build/outputs/apk/release/lx-music-mobile-v${{ env.PACKAGE_VERSION }}-arm64-v8a.apk

      - name: Upload Artifact armeabi-v7a
        uses: actions/upload-artifact@v3
        with:
          name: app-v${{ env.PACKAGE_VERSION }}-armeabi-v7a-release
          path: android/app/build/outputs/apk/release/lx-music-mobile-v${{ env.PACKAGE_VERSION }}-armeabi-v7a.apk

      - name: Upload Artifact universal
        uses: actions/upload-artifact@v3
        with:
          name: app-v${{ env.PACKAGE_VERSION }}-universal-release
          path: android/app/build/outputs/apk/release/lx-music-mobile-v${{ env.PACKAGE_VERSION }}-universal.apk

      - name: Upload Artifact x86_64
        uses: actions/upload-artifact@v3
        with:
          name: app-v${{ env.PACKAGE_VERSION }}-x86_64-release
          path: android/app/build/outputs/apk/release/lx-music-mobile-v${{ env.PACKAGE_VERSION }}-x86_64.apk

      - name: Upload Artifact x86
        uses: actions/upload-artifact@v3
        with:
          name: app-v${{ env.PACKAGE_VERSION }}-x86-release
          path: android/app/build/outputs/apk/release/lx-music-mobile-v${{ env.PACKAGE_VERSION }}-x86.apk
